from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_fee_receipt(fee, filename):
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # ==========================
    # Header
    # ==========================
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, 800, "Football Academy Fee Receipt")

    c.setFont("Helvetica", 11)
    c.drawCentredString(
        width / 2,
        780,
        "Football Academy Management System"
    )

    c.drawCentredString(
        width / 2,
        765,
        "Professional Fee Receipt"
    )

    c.line(50, 745, 550, 745)

    # ==========================
    # Player Details
    # ==========================
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 715, "Player Details")

    c.setFont("Helvetica", 12)
    c.drawString(50, 690, f"Player Name : {fee.player.full_name}")
    c.drawString(50, 670, f"Player ID : {fee.player.id}")

    c.line(50, 645, 550, 645)

    # ==========================
    # Fee Details
    # ==========================
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 620, "Fee Details")

    c.setFont("Helvetica", 12)

    c.drawString(50, 595, f"Receipt No : {fee.id}")
    c.drawString(50, 575, f"Voucher No : {fee.voucher_no}")
    c.drawString(50, 555, f"Month : {fee.month}")
    c.drawString(50, 535, f"Amount : PKR {fee.amount}")
    c.drawString(50, 515, f"Status : {fee.status}")
    c.drawString(50, 495, f"Due Date : {fee.due_date}")
    c.drawString(50, 475, "Payment Mode : Cash / Online")

    if hasattr(fee, "payment_date") and fee.payment_date:
        c.drawString(
            50,
            455,
            f"Payment Date : {fee.payment_date.strftime('%d-%m-%Y %H:%M')}"
        )

    # ==========================
    # Signature
    # ==========================
    c.line(50, 400, 180, 400)
    c.drawString(60, 385, "Authorized Signature")

    c.line(360, 400, 520, 400)
    c.drawString(405, 385, "Academy Stamp")

    # ==========================
    # Footer
    # ==========================
    c.line(50, 350, 550, 350)

    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(
        width / 2,
        330,
        "Generated by Football Academy Management System"
    )

    c.save()
    return filename
